package voterregistration


class Parcel {
	String pin
	String owner_name
	String address1
	String address2
	String owner_city
	String owner_stat
	String owner_zip
	String property_a
	String address_la
	String house
	String street_dir
	String street_nam
	String street_typ
	String apartment
	String prop_city
	String prop_zip
	String sec_twn_rn
	String addition_n
	String block
	String lot
	String legal1
	String legal2
	String legal3
	String legal4
	String admin
	String fieldbook
	String land_value
	String improvemen
	String total_valu
	String dcalegal
	String dcaacctype
	String property_class
	String town
	String sid
	String tax_dist
	String school_dis
	String esu
	String city
	String mud
	String fire_dist
	String ota
	String county_lib
	String redevlpmnt
	String numbldgs
	String bldg_numb
	String bldg_sf
	String bldg_story
	String bldg_strht
	String bldg_yrblt
	String bldg_desc
	String condo
	String subno
	String owner
	String acres
	String sq_feet
	String assessor
	String treasurer
	String x_coord
	String y_coord
	String shape_leng
	String shape_area
    static constraints = {
	pin        (nullable:true)
        owner_name (nullable:true)
        address1   (nullable:true)
        address2   (nullable:true)
        owner_city (nullable:true)
        owner_stat (nullable:true)
        owner_zip  (nullable:true)
        property_a (nullable:true)
        address_la (nullable:true)
        house      (nullable:true)
        street_dir (nullable:true)
        street_nam (nullable:true)
        street_typ (nullable:true)
        apartment  (nullable:true)
        prop_city  (nullable:true)
        prop_zip   (nullable:true)
        sec_twn_rn (nullable:true)
        addition_n (nullable:true)
        block      (nullable:true)
        lot        (nullable:true)
        legal1     (nullable:true)
        legal2     (nullable:true)
        legal3     (nullable:true)
        legal4     (nullable:true)
        admin      (nullable:true)
        fieldbook  (nullable:true)
        land_value (nullable:true)
        improvemen (nullable:true)
        total_valu (nullable:true)
        dcalegal   (nullable:true)
        dcaacctype (nullable:true)
        property_class(nullable:true)
        town       (nullable:true)
        sid        (nullable:true)
        tax_dist   (nullable:true)
        school_dis (nullable:true)
        esu        (nullable:true)
        city       (nullable:true)
        mud        (nullable:true)
        fire_dist  (nullable:true)
        ota        (nullable:true)
        county_lib (nullable:true)
        redevlpmnt (nullable:true)
        numbldgs   (nullable:true)
        bldg_numb  (nullable:true)
        bldg_sf    (nullable:true)
        bldg_story (nullable:true)
        bldg_strht (nullable:true)
        bldg_yrblt (nullable:true)
        bldg_desc  (nullable:true)
        condo      (nullable:true)
        subno      (nullable:true)
        owner      (nullable:true)
        acres      (nullable:true)
        sq_feet    (nullable:true)
        assessor   (nullable:true)
        treasurer  (nullable:true)
        x_coord    (nullable:true)
        y_coord    (nullable:true)
        shape_leng (nullable:true)
        shape_area (nullable:true)
	
    }
	
	static mapping = {
	}
}
